# Generated by Django 5.1.3 on 2024-11-28 23:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wgroup',
            fields=[
                ('group_id', models.CharField(default='8ac93f0a006d47faa08a052e0e34bea3', max_length=32, primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField(max_length=70)),
                ('language', models.CharField(choices=[('Akan', 'Akan'), ('Albanian', 'Albanian'), ('Alemannic', 'Alemannic'), ('Amharic', 'Amharic'), ('Antiguan Creole', 'Antiguan Creole'), ('Arabic', 'Arabic'), ('Armenian', 'Armenian'), ('Azerbaijani', 'Azerbaijani'), ('Bajan Creole', 'Bajan Creole'), ('Bambara', 'Bambara'), ('Bemba', 'Bemba'), ('Bengali', 'Bengali'), ('Berber', 'Berber'), ('Bislama', 'Bislama'), ('Bosnian', 'Bosnian'), ('Bulgarian', 'Bulgarian'), ('Burmese', 'Burmese'), ('Catalan', 'Catalan'), ('Chichewa', 'Chichewa'), ('Chittagonian', 'Chittagonian'), ('Chuukese', 'Chuukese'), ('Comorian', 'Comorian'), ('Croatian', 'Croatian'), ('Czech', 'Czech'), ('Dari', 'Dari'), ('Dhivehi', 'Dhivehi'), ('Dioula', 'Dioula'), ('Dzongkha', 'Dzongkha'), ('English', 'English'), ('Ewe', 'Ewe'), ('Fijian', 'Fijian'), ('Filipino', 'Filipino'), ('Finnish', 'Finnish'), ('Fon', 'Fon'), ('Forro', 'Forro'), ('French', 'French'), ('Frisian', 'Frisian'), ('Gaelic (Irish)', 'Gaelic (Irish)'), ('Garifuna', 'Garifuna'), ('Georgian', 'Georgian'), ('Gilbertese', 'Gilbertese'), ('Greek', 'Greek'), ('Grenadian Creole', 'Grenadian Creole'), ('Haitian Creole', 'Haitian Creole'), ('Hausa', 'Hausa'), ('Hebrew', 'Hebrew'), ('Hindi', 'Hindi'), ('Hungarian', 'Hungarian'), ('Icelandic', 'Icelandic'), ('Indonesian', 'Indonesian'), ('Irish', 'Irish'), ('Isan', 'Isan'), ('Italian', 'Italian'), ('Javanese', 'Javanese'), ('Jamaican Patois', 'Jamaican Patois'), ('Kazakh', 'Kazakh'), ('Kinyarwanda', 'Kinyarwanda'), ('Kirundi', 'Kirundi'), ('Kituba', 'Kituba'), ('Korean', 'Korean'), ('Kurdish', 'Kurdish'), ('Lao', 'Lao'), ('Latin', 'Latin'), ('Latvian', 'Latvian'), ('Lingala', 'Lingala'), ('Luxembourgish', 'Luxembourgish'), ('Malagasy', 'Malagasy'), ('Malay', 'Malay'), ('Maltese', 'Maltese'), ('Mandarin', 'Mandarin'), ('Maori', 'Maori'), ('Marshallese', 'Marshallese'), ('Mirandese', 'Mirandese'), ('Mongolian', 'Mongolian'), ('Montenegrin', 'Montenegrin'), ('Mossi', 'Mossi'), ('Nahuatl', 'Nahuatl'), ('Nauruan', 'Nauruan'), ('Nepali', 'Nepali'), ('Norwegian', 'Norwegian'), ('Oromo', 'Oromo'), ('Palauan', 'Palauan'), ('Persian (Farsi)', 'Persian (Farsi)'), ('Pijin', 'Pijin'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Punjabi', 'Punjabi'), ('Quechua', 'Quechua'), ('Romanian', 'Romanian'), ('Russian', 'Russian'), ('Samoan', 'Samoan'), ('Serbian', 'Serbian'), ('Setswana', 'Setswana'), ('Sharchhopka', 'Sharchhopka'), ('Shona', 'Shona'), ('Sinhala', 'Sinhala'), ('Slovak', 'Slovak'), ('Slovenian', 'Slovenian'), ('Somali', 'Somali'), ('Spanish', 'Spanish'), ('Sranan Tongo', 'Sranan Tongo'), ('Swahili', 'Swahili'), ('Swedish', 'Swedish'), ('Tagalog', 'Tagalog'), ('Tajik', 'Tajik'), ('Tamil', 'Tamil'), ('Tatar', 'Tatar'), ('Tetum', 'Tetum'), ('Thai', 'Thai'), ('Tibetan', 'Tibetan'), ('Tigrinya', 'Tigrinya'), ('Tok Pisin', 'Tok Pisin'), ('Tsonga', 'Tsonga'), ('Tuvaluan', 'Tuvaluan'), ('Urdu', 'Urdu'), ('Uzbek', 'Uzbek'), ('Vincentian Creole', 'Vincentian Creole'), ('Vietnamese', 'Vietnamese'), ('Wayuu', 'Wayuu'), ('Welsh', 'Welsh'), ('Wolof', 'Wolof'), ('Zulu', 'Zulu')], max_length=50)),
                ('category', models.CharField(choices=[('family_friends', 'Family and Friends'), ('work_professional', 'Work and Professional'), ('education_learning', 'Education and Learning'), ('hobbies_interests', 'Hobbies and Interests'), ('events_social', 'Events and Social Activities'), ('community_social', 'Community and Social Causes'), ('business_entrepreneurship', 'Business and Entrepreneurship'), ('entertainment_media', 'Entertainment and Media'), ('health_wellness', 'Health and Wellness'), ('religious_spiritual', 'Religious and Spiritual'), ('shopping_deals', 'Shopping and Deals'), ('parenting_family', 'Parenting and Family'), ('coding_programming', 'Coding and Programming'), ('technology_gaming', 'Technology and Gaming'), ('sports_fitness', 'Sports and Fitness'), ('support_groups', 'Support Groups')], default='family_friends', max_length=50)),
                ('tags', models.CharField(help_text='Enter up to 5 tags separated by commas (max 200 characters)', max_length=200)),
                ('nsfw', models.BooleanField(default=False, help_text='Mark this group as NSFW')),
                ('description', models.TextField()),
                ('group_image', models.ImageField(blank=True, null=True, upload_to='groupimage/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('whatsapplink', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WReview',
            fields=[
                ('review_id', models.CharField(default='e11e366d6ba8483da2d3cbb98e9c0f2a', max_length=32, primary_key=True, serialize=False, unique=True)),
                ('rating', models.IntegerField()),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatgroup.wgroup')),
            ],
        ),
    ]
