# Generated by Django 5.1.3 on 2024-11-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatgroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wgroup',
            name='group_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wreview',
            name='review_id',
            field=models.CharField(default='513efd4255444402812f5c7481527bd0', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
