# Generated by Django 5.1.3 on 2024-11-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatgroup', '0002_wgroup_created_at_wgroup_updated_at_wreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wgroup',
            name='language',
            field=models.CharField(choices=[('Akan', 'Akan'), ('Albanian', 'Albanian'), ('Alemannic', 'Alemannic'), ('Amharic', 'Amharic'), ('Antiguan Creole', 'Antiguan Creole'), ('Arabic', 'Arabic'), ('Armenian', 'Armenian'), ('Azerbaijani', 'Azerbaijani'), ('Bajan Creole', 'Bajan Creole'), ('Bambara', 'Bambara'), ('Bemba', 'Bemba'), ('Bengali', 'Bengali'), ('Berber', 'Berber'), ('Bislama', 'Bislama'), ('Bosnian', 'Bosnian'), ('Bulgarian', 'Bulgarian'), ('Burmese', 'Burmese'), ('Catalan', 'Catalan'), ('Chichewa', 'Chichewa'), ('Chittagonian', 'Chittagonian'), ('Chuukese', 'Chuukese'), ('Comorian', 'Comorian'), ('Croatian', 'Croatian'), ('Czech', 'Czech'), ('Dari', 'Dari'), ('Dhivehi', 'Dhivehi'), ('Dioula', 'Dioula'), ('Dzongkha', 'Dzongkha'), ('English', 'English'), ('Ewe', 'Ewe'), ('Fijian', 'Fijian'), ('Filipino', 'Filipino'), ('Finnish', 'Finnish'), ('Fon', 'Fon'), ('Forro', 'Forro'), ('French', 'French'), ('Frisian', 'Frisian'), ('Gaelic (Irish)', 'Gaelic (Irish)'), ('Garifuna', 'Garifuna'), ('Georgian', 'Georgian'), ('Gilbertese', 'Gilbertese'), ('Greek', 'Greek'), ('Grenadian Creole', 'Grenadian Creole'), ('Haitian Creole', 'Haitian Creole'), ('Hausa', 'Hausa'), ('Hebrew', 'Hebrew'), ('Hindi', 'Hindi'), ('Hungarian', 'Hungarian'), ('Icelandic', 'Icelandic'), ('Indonesian', 'Indonesian'), ('Irish', 'Irish'), ('Isan', 'Isan'), ('Italian', 'Italian'), ('Javanese', 'Javanese'), ('Jamaican Patois', 'Jamaican Patois'), ('Kazakh', 'Kazakh'), ('Kinyarwanda', 'Kinyarwanda'), ('Kirundi', 'Kirundi'), ('Kituba', 'Kituba'), ('Korean', 'Korean'), ('Kurdish', 'Kurdish'), ('Lao', 'Lao'), ('Latin', 'Latin'), ('Latvian', 'Latvian'), ('Lingala', 'Lingala'), ('Luxembourgish', 'Luxembourgish'), ('Malagasy', 'Malagasy'), ('Malay', 'Malay'), ('Maltese', 'Maltese'), ('Mandarin', 'Mandarin'), ('Maori', 'Maori'), ('Marshallese', 'Marshallese'), ('Mirandese', 'Mirandese'), ('Mongolian', 'Mongolian'), ('Montenegrin', 'Montenegrin'), ('Mossi', 'Mossi'), ('Nahuatl', 'Nahuatl'), ('Nauruan', 'Nauruan'), ('Nepali', 'Nepali'), ('Norwegian', 'Norwegian'), ('Oromo', 'Oromo'), ('Palauan', 'Palauan'), ('Persian (Farsi)', 'Persian (Farsi)'), ('Pijin', 'Pijin'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Punjabi', 'Punjabi'), ('Quechua', 'Quechua'), ('Romanian', 'Romanian'), ('Russian', 'Russian'), ('Samoan', 'Samoan'), ('Serbian', 'Serbian'), ('Setswana', 'Setswana'), ('Sharchhopka', 'Sharchhopka'), ('Shona', 'Shona'), ('Sinhala', 'Sinhala'), ('Slovak', 'Slovak'), ('Slovenian', 'Slovenian'), ('Somali', 'Somali'), ('Spanish', 'Spanish'), ('Sranan Tongo', 'Sranan Tongo'), ('Swahili', 'Swahili'), ('Swedish', 'Swedish'), ('Tagalog', 'Tagalog'), ('Tajik', 'Tajik'), ('Tamil', 'Tamil'), ('Tatar', 'Tatar'), ('Tetum', 'Tetum'), ('Thai', 'Thai'), ('Tibetan', 'Tibetan'), ('Tigrinya', 'Tigrinya'), ('Tok Pisin', 'Tok Pisin'), ('Tsonga', 'Tsonga'), ('Tuvaluan', 'Tuvaluan'), ('Urdu', 'Urdu'), ('Uzbek', 'Uzbek'), ('Vincentian Creole', 'Vincentian Creole'), ('Vietnamese', 'Vietnamese'), ('Wayuu', 'Wayuu'), ('Welsh', 'Welsh'), ('Wolof', 'Wolof'), ('Zulu', 'Zulu')], max_length=50),
        ),
    ]
