# Generated by Django 5.1.3 on 2024-11-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatgroup', '0003_alter_wgroup_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='wgroup',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='groupimage/'),
        ),
    ]
